interface Address {
  id: number;
  order_id: number;
  address1: string;
  address2: string;
  address: string;
  house_no: string;
  compartment: string;
  neighborhood: string;
  city: string;
  company: string;
  country: string;
  first_name: string;
  last_name: string;
  latitude: string;
  longitude: string;
  phone: string;
  province: string;
  zip: string;
  name: string;
  country_code: string;
  province_code: string;
  type: string;
  created_at: string;
  updated_at: string;
}

interface Customer {
  id: number;
  shop_id: number;
  global_customer_id: string | null;
  first_name: string;
  last_name: string;
  email: string;
  phone: string;
  cpf: string;
  cnpj: string;
  state_reg_num: string | null;
  cpn: string | null;
  house_number: string | null;
  tax_exempt: number;
  email_marketing: number;
  phone_marketing: number;
  source: string;
  tags: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
  paypal_payer_id: string | null;
  session_key: string | null;
  cartpanda_pay_at: string | null;
  cartpanda_pay_customer_id: string | null;
  full_name: string;
}

interface Order {
  id: number;
  shop_id: number;
  customer_id: number;
  user_id: number;
  location_id: number;
  dsers_batch_id: string | null;
  processed_in_dsers: string | null;
  tiny_erp_id: string | null;
  test: number;
  shipping_lines: string;
  name: string;
  subtotal_price: number;
  subtotal_price_set: number;
  total_discounts: number;
  total_discounts_set: number;
  total_line_items_price: number;
  total_line_items_price_set: number;
  total_price: number;
  total_price_set: number;
  total_tax: number;
  total_tax_set: number;
  total_tip_received: number;
  total_weight: number;
  no_of_installments: number;
  installments_rate: number;
  order_status_url: string;
  email: string;
  legal_entity: string;
  is_archived: number;
  billing_address_id: number;
  shipping_address_id: number;
  browser_ip: string;
  buyer_accepts_marketing: number;
  buyer_accepts_phone_marketing: number;
  cancel_reason: string;
  cart_token: string;
  client_details: string;
  currency: string;
  customer_locale: string;
  discount_applications: string;
  discount_codes: string;
  landing_site: string;
  note: string;
  note_attributes: string;
  custom_notes: string;
  number: number;
  order_number: string;
  payment_details: string | null;
  payment_gateway_names: string | null;
  phone: string;
  presentment_currency: string;
  processing_method: string;
  referring_site: string;
  source_name: string;
  tags: string | null;
  tax_lines: number;
  taxes_included: number;
  token: string;
  card_token: string;
  customer_token: string;
  cvv: string;
  is_sync: number;
  in_progress: number;
  is_woocommerce_sync: number;
  is_magento_sync: number;
  status_id: string;
  fulfillment_status: string;
  chargeback_received: number;
  processed_at: string;
  cancelled_at: string | null;
  closed_at: string | null;
  boleto_email_sent: number;
  cartxpayment_transaction_id: string;
  created_at: string;
  updated_at: string;
  order_comment: string | null;
  is_cartx_test: number;
  paypal_order_id: string | null;
  temp_paypal: number;
  pagseguro_ccCPF: string;
  antifraud_synced_at: string | null;
  user_agent: string;
  is_cp_pay: string;
  subtotal_price_in_decimal: string | null;
  total_price_in_decimal: string | null;
  payment_gateway_token: string | null;
  payment_status: number;
  appmax_payment_token: string;
  payment_gateway: string;
  boleto_code: string;
  boleto_link: string;
  boleto_limit_date: string;
  pix_code: string | null;
  pix_limit_date: string | null;
  payment_type: string;
  tracking_number: string | null;
  tracking_numbers: string | null;
  afid: string | null;
  affiliate_amount: string | null;
  affiliate_slug: string | null;
  coproducer_amount: string | null;
  coproducer_slug: string | null;
  shopify_order_id: string | null;
  thank_you_page: string;
  total_price_without_tax: number;
  address: Address;
  line_items: object[];
  customer: Customer;
  orders_shippings: object[];
  fulfillments: object[];
  tracking_parameters: object[];
  shop: object;
  all_payments: object[];
  checkout_params: object;
  payment: object;
  shop_info: object;
  local_currency_amount_without_tax: string;
  transactions: object[];
  digital_attachment: string;
  checkout_link: string;
}

interface Webhook {
  id: number;
  endpoint: string;
  shop_id: number;
  apply_for: string;
  webhooks_to_product: string | null;
  webhooks_to_collection: string | null;
}

export interface WebhookPayload {
  event: string;
  order: Order;
  webhook: Webhook;
}
